# Site settings
title: "Hoshizora Chi"
SEOTitle: Hoshizora Chi Blog
header-img: img/AyakaCompressed.png
favicon: img/favicon.ico
email: ciii1@proton.me
description: "Spreading beautiful messages from around the world"
keyword: "hoshizora chi, chi, @ciii1, translation, japanese"
url: "https://hoshizora-chi.github.io" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
github_username: hoshizora-chi
twitter_username: _ciii1
facebook_username: false
linkedin_username: false

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
service-worker: true
paginate: 10
featured-tags: false
exclude:
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md
  - README.zh.md
page-mathjax: false
anchorjs: true
