highlighter: rouge
SEOTitle: Penerbit Yayasan Fudhail bin Iyadh
description: Spreading beautiful messages from around the world
keyword: buku anak, buku
email: yysfudhailbiniyadh@gmail.com
url: https://penerbityayasanfudhailbiniyadh.com
header-img: /img/potdarirumah.jpg
github_username: ""
twitter_username: ""
future: true
permalink: pretty
markdown: kramdown
facebook_username: false
RSS: false
favicon: img/favicon.ico
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
service-worker: true
paginate: 10
title: Penerbit Yayasan Fudhail Bin Iyadh
linkedin_username: false
featured-tags: false
exclude:
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md
  - README.zh.md
page-mathjax: false
baseurl: https://penerbityayasanfudhailbiniyadh.com/
anchorjs: true
