plugins:
  - jekyll-paginate
highlighter: rouge
title: Penerbit Yayasan Fudhail bin Iyadh
SEOTitle: Penerbit Yayasan Fudhail bin Iyadh
description: Deskripsi
keyword: penerbit
email: yysfudhailbiniyadh@gmail.com
url: https://penerbityayasanfudhailbiniyadh.com
baseurl: https://penerbityayasanfudhailbiniyadh.com
header-img: /img/AyakaCompressed.png
github_username: ""
twitter_username: ""
future: true
linkedin_username: false
RSS: false
sidebar: true
sidebar-avatar: /img/AyakaCompressed.png
sidebar-about-description: My mission is to spread the beauty of messages from around the world.
ga_domain: huangxuan.me
netease_comment: false
permalink: pretty
markdown: kramdown
facebook_username: false
featured-condition-size: 0
ga_track_id: UA-49627206-1
chrome-tab-theme-color: "#df8e1d"
friends:
  - title: Leapofod
    href: https://github.com/Leapofod
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
service-worker: true
paginate: 10
featured-tags: false
exclude:
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md
  - README.zh.md
page-mathjax: false
anchorjs: true
