plugins:
  - jekyll-paginate
highlighter: rouge
keyword: buku anak, buku
header-img: img/potdarirumah.jpg
twitter_username: ""
future: true
title: Penerbit Yayasan Fudhail Bin Iyadh
SEOTitle: Penerbit Yayasan Fudhail bin Iyadh
description: Spreading beautiful messages from around the world
email: yysfudhailbiniyadh@gmail.com
favicon: img/potdarirumah.jpg
github_username: ""
instagram_username: ""
permalink: pretty
url: https://penerbityayasanfudhailbiniyadh.com
facebook_username: ""
zhihu_username: ""
weibo_username: ""
markdown: kramdown
RSS: false
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
service-worker: true
paginate: 10
linkedin_username: ""
featured-tags: false
exclude:
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md
  - README.zh.md
page-mathjax: false
anchorjs: true
