highlighter: rouge
SEOTitle: Penerbit Yayasan Fudhail bin Iyadh
description: Spreading beautiful messages from around the world
keyword: buku anak, buku
email: yysfudhailbiniyadh@gmail.com
url: https://localhost:4000
header-img: img/potdarirumah.jpg
github_username: ""
twitter_username: ""
instagram_username: ""
facebook_username: ""
linkedin_username: ""
zhihu_username: ""
weibo_username: ""
future: true
permalink: pretty
markdown: kramdown
RSS: false
favicon: img/favicon.ico
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
service-worker: true
paginate: 10
plugins: [jekyll-paginate]
title: Penerbit Yayasan Fudhail Bin Iyadh
featured-tags: false
exclude:
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md
  - README.zh.md
page-mathjax: false
anchorjs: true
