plugins:
  - jekyll-paginate
highlighter: rouge
title: Penerbit Yayasan Fudhail Bin Iyadh
SEOTitle: Penerbit Yayasan Fudhail bin Iyadh
description: Spreading beautiful messages from around the world
keyword: buku anak, buku
email: yysfudhailbiniyadh@gmail.com
url: https://penerbityayasanfudhailbiniyadh.com
header-img: img/potdarirumah.jpg
favicon: img/potdarirumah.jpg
github_username: yysfudhailbiniyadh
twitter_username: ""
future: true
instagram_username: ""
facebook_username: ""
zhihu_username: ""
weibo_username: ""
RSS: false
sidebar-avatar: img/potdarirumah.jpg
sidebar-about-description: Yayasan Fudhail bin Iyadh adalah yayasan yang
  bergerak dalam bidang pendidikan dan penerbitan
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
service-worker: true
paginate: 10
linkedin_username: ""
featured-tags: false
exclude:
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md
  - README.zh.md
page-mathjax: false
anchorjs: true
